<?php 
    echo $block->getButtonHtml();
?>
<script>
require([
    'jquery',
    'prototype',
], function($){
	
    function test_unit(){
		$("#test_unit_testunit_config_json_response").val('');
		var additional = $("#test_unit_testunit_config_url_addition").val();
		var action = $("#test_unit_testunit_config_action").val();
		var body = $("#test_unit_testunit_config_json_request").val();
        params = {additional: additional, action : action, body: body};
        new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
            loaderArea:     true,
            asynchronous:   true,
            parameters:     params,
            onSuccess: function(transport) {
				console.log(transport);
                var response = JSON.parse(transport.responseJSON);
				var formattedJson = JSON.stringify(response, null, '\t');
				$("#test_unit_testunit_config_json_response").attr('rows','15');
				$("#test_unit_testunit_config_json_response").val(formattedJson);
            }
			
        });
    }
    $('#btn_id').click(function(){
        test_unit();
    });
	$('#save').hide();
});
</script>