<?php 
    echo $block->getButtonHtml();
?>
<script>
require([
    'jquery',
    'prototype',
], function($){
    function sync(){
        new Ajax.Request('<?php echo $block->getAjaxUrl() ?>', {
            loaderArea:     true,
            asynchronous:   true,
            onSuccess: function(response) {
				
            },
			onError: function(response) {
				
            }
        });
    }
    $('#sync_id').click(function(){
        sync();
    });
});
</script>